version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://bkashishh07:WrIzv49gynwO@ep-square-dew-a5fv8u6f.us-east-2.aws.neon.tech/Bitespeed?sslmode=require
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_postgres_user
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_database_name
    ports:
      - "5433:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
